In [1]:
# plots to check distribution of TF dataset - should already be TPM normalised and log10 transformed
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#change this to folder in which 'Full data files' folder is in
DATA_ROOT = '/Users/alexanderbroadley/Documents/PhD/Zhang Lab/Zhang_Lab_Code/MML_model/data'

#load TF dataset
gene_expressions = pd.read_csv((f"{DATA_ROOT}/Full data files/Geneexpression (full).tsv"), sep='\t', header=0)
TF_expressions = pd.read_csv((f"{DATA_ROOT}/Full data files/TF(full).tsv"), sep='\t', header=0)

In [2]:
gene_expressions

,A1BG,A2M,A2ML1,A3GALT2,A4GALT,AAAS,AACS,AADAT,AAGAB,AAK1,...,ZW10,ZWILCH,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,1.103037,2.453714,0.080932,0.149036,1.638797,1.510672,0.576105,0.706676,1.352335,0.725572,...,1.227141,0.890839,0.668930,0.746892,1.340183,0.186207,1.087373,2.373830,1.297430,1.223110
1,0.315785,2.406065,0.298752,0.000000,0.544888,0.501931,0.587212,0.631842,1.097837,0.882588,...,1.120169,0.466563,0.807861,0.782115,0.649692,0.118296,1.385296,0.882246,1.020247,1.380291
2,0.630826,2.498732,0.148162,0.021514,0.634572,1.738609,0.970243,1.055886,1.735581,0.833921,...,1.620812,1.622782,0.594452,1.156181,1.129571,1.008971,1.292981,1.889968,1.079429,1.279160
3,0.777204,2.493352,0.209044,0.027975,0.705359,1.769358,1.009512,1.035604,1.683556,0.805440,...,1.570029,1.561268,0.652413,1.111955,1.164511,0.981551,1.216450,2.008608,1.116350,1.239703
4,0.736857,2.478016,0.134237,0.051799,0.746096,1.769308,1.004919,1.041937,1.711269,0.823459,...,1.610865,1.585686,0.561892,1.112633,1.139375,0.969589,1.256989,1.992561,1.087913,1.246616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15930,0.082311,0.134569,0.024612,0.000000,1.561996,1.781711,1.262138,0.502096,1.918435,0.887044,...,1.732514,1.926070,0.776040,1.248146,1.324217,1.322226,1.230879,2.283736,1.261986,1.546062
15931,0.071488,0.170652,0.000000,0.069988,1.526367,1.756801,1.248976,0.419333,1.894454,0.919907,...,1.719399,1.952550,0.728295,1.136292,1.356000,1.335564,1.253777,2.265058,1.282164,1.602514
15932,0.019623,0.166750,0.011075,0.133972,1.553726,1.761157,1.241091,0.550421,1.908960,0.872621,...,1.692848,1.938360,0.698932,1.166513,1.281206,1.357463,1.225619,2.267667,1.252374,1.570008
15933,0.077525,0.137069,0.045015,0.000000,1.698391,1.608943,1.126351,0.618856,1.855709,0.977807,...,1.488789,1.805041,0.710359,1.257009,1.215786,1.160957,1.293212,1.949554,0.934495,1.330625
15934,0.024247,0.098437,0.013716,0.000000,1.809723,1.658431,1.193593,0.364421,1.833066,0.748412,...,1.300537,1.531979,0.486517,1.027820,1.201754,1.192493,0.947573,2.045025,0.881081,0.938150

In [3]:
original_GE = np.power(10, gene_expressions) - 1

In [4]:
original_TF = np.power(10, TF_expressions) - 1

In [8]:
original_GE.to_csv(f'{DATA_ROOT}/Genexpression_TPM.tsv', sep = '\t', index = False)
original_TF.to_csv(f'{DATA_ROOT}/TF_TPM.tsv', sep = '\t', index=False)

In [15]:
working_GE = pd.read_csv((f"{DATA_ROOT}/Full data files/Genexpression_TPM.tsv"), sep='\t', header=0, index_col=0)
working_TE = pd.read_csv((f"{DATA_ROOT}/Full data files/TF_TPM.tsv"), sep='\t', header=0, index_col=0)

In [16]:
working_GE

,A1BG,A2M,A2ML1,A3GALT2,A4GALT,AAAS,AACS,AADAT,AAGAB,AAK1,...,ZW10,ZWILCH,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,11.677592,283.258604,0.204846,0.409406,42.530798,31.409461,2.767951,4.089511,21.507914,4.315844,...,15.871011,6.777480,3.665841,4.583312,20.886828,0.535350,11.228481,235.499431,18.834879,15.715137
1,1.069119,253.721141,0.989539,0.000000,2.506613,2.176369,2.865554,3.283930,11.526704,6.631113,...,12.187694,1.927943,5.424818,5.055012,3.463668,0.313096,23.282625,6.625113,9.477245,23.004396
2,3.273916,314.305639,0.406571,0.050786,3.310941,53.778415,8.337765,10.373293,53.397790,5.822153,...,40.764947,40.954817,2.930540,13.327848,12.476315,9.208706,18.632758,76.618924,11.006856,18.017770
3,4.986921,310.423985,0.618243,0.066534,4.074100,57.797364,9.221439,9.854357,47.256484,5.389104,...,36.155982,35.413948,3.491725,11.940614,13.605333,8.584102,15.460754,101.001947,12.072245,16.366143
4,4.455780,299.618585,0.362186,0.126677,4.573094,57.790637,9.113901,10.013795,50.436242,5.659762,...,39.819240,37.520010,2.646629,11.960828,12.783979,8.323706,17.071302,97.301803,11.243720,16.644757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15930,0.208678,0.363229,0.058308,0.000000,35.475057,59.493837,17.286831,2.177574,81.877246,6.709813,...,53.014952,83.347041,4.970900,16.707042,20.096835,20.000328,16.016836,191.192278,17.280422,34.161059
15931,0.178930,0.481332,0.000000,0.174864,32.602144,56.121721,16.740901,1.626233,77.424878,7.315855,...,51.408144,88.649975,4.349274,12.686493,21.698638,20.655306,16.938109,183.101778,18.149775,39.041866
15932,0.046220,0.468081,0.025829,0.361356,34.787035,56.697436,16.421718,2.551576,80.088623,6.457980,...,48.300149,85.767992,3.999561,13.672797,18.107594,21.775246,15.811993,184.211307,16.880263,36.154183
15933,0.195433,0.371101,0.109214,0.000000,48.933407,39.639042,12.376749,3.157730,70.731273,8.501818,...,29.816910,62.832374,4.132860,17.072112,15.435617,13.486277,18.643197,88.033673,7.599926,20.410394
15934,0.057419,0.254404,0.032087,0.000000,63.524291,44.543931,14.616832,1.314308,67.087347,4.602885,...,18.977296,33.039157,2.065608,9.661540,14.913069,14.577330,7.862843,109.923974,6.604680,7.672606