# Examining differences in distributions

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy import stats

In [64]:
target = 'MBOAT7'

In [65]:
#for now manually load dist for one target gene
male_target_contribs = pd.read_csv(f'./data/male_contribution_dists/{target}_reg_cont_distributions.csv', index_col = 0)
female_target_contribs = pd.read_csv(f'./data/female_contribution_dists/{target}_reg_cont_distributions.csv', index_col = 0)

# Effect Size Difference Approach

In [66]:
male_target_contribs = male_target_contribs.fillna(0)
female_target_contribs = female_target_contribs.fillna(0)

In [67]:
male_target_contribs

,ADNP,ADNP2,AEBP1,AEBP2,AHR,AHRR,AIRE,AKNA,ALX4,AR,...,ZSCAN22,ZSCAN23,ZSCAN26,ZSCAN29,ZSCAN31,ZSCAN4,ZSCAN5A,ZSCAN9,ZXDA,ZXDC
0,-0.003126,0.000005,0.022339,-0.000193,0.009005,-0.000124,-0.000083,-0.001430,-0.000028,0.000610,...,0.000013,0.000166,-0.000220,-0.010690,0.000274,0.008390,0.004538,0.000030,-0.000042,0.012300
1,-0.003240,0.000005,0.021931,-0.000186,0.009437,-0.000156,-0.000087,0.000023,-0.000030,0.000463,...,0.000031,0.000174,-0.000242,-0.011036,0.000318,0.008784,0.003539,0.000031,-0.000052,0.011493
2,-0.003463,0.000006,0.023411,-0.000168,0.010078,-0.000166,-0.000093,0.000118,-0.000032,0.000454,...,0.000050,0.000186,-0.000260,-0.011820,0.000349,0.009377,0.003778,0.000034,-0.000047,0.009846
3,-0.003617,0.000006,0.018591,-0.000171,0.010507,-0.000173,-0.000096,0.000016,-0.000033,0.000473,...,0.000052,0.000193,-0.000284,-0.012315,0.000359,0.009769,0.006423,0.000036,-0.000022,0.013177
4,-0.003452,0.000006,0.023298,-0.000152,0.010031,-0.000148,-0.000092,0.000024,-0.000031,0.000454,...,0.000014,0.000185,-0.000255,-0.011745,0.000342,0.009331,0.009327,0.000035,-0.000042,0.011805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,-0.004182,0.000014,0.026326,-0.000134,0.012410,-0.000204,-0.000114,0.000092,-0.000039,0.000597,...,-0.005009,0.000228,-0.000347,-0.014051,0.000460,0.011515,0.004640,0.000029,0.000104,0.007170
709,-0.002683,0.000003,0.019859,-0.000188,0.007633,-0.000126,-0.000070,-0.008173,-0.000024,0.000651,...,0.000106,0.000141,-0.000180,-0.009138,0.000224,0.002558,0.007595,0.000029,-0.000055,0.013400
710,-0.002752,0.000003,0.020309,-0.000203,0.007828,-0.000116,-0.000072,-0.007811,-0.000025,0.000674,...,0.000108,0.000145,-0.000185,-0.009382,0.000227,0.007309,0.008571,0.000027,-0.000047,0.012982
711,-0.002416,0.000003,0.018580,-0.000198,0.006845,-0.000083,-0.000063,-0.009288,-0.000022,0.000572,...,0.000141,0.000127,-0.000163,-0.008233,0.000197,0.002295,0.008908,0.000028,-0.000066,0.012957
712,-0.002406,0.000002,0.018534,-0.000199,0.006815,-0.000080,-0.000063,-0.009290,-0.000021,0.000568,...,0.000155,0.000178,-0.000157,-0.008216,0.000196,0.002285,0.009455,0.000027,-0.000061,0.012946

In [68]:
#iterate through TFs in male_target_contribs (same as in female)
results_df = pd.DataFrame(index = male_target_contribs.columns, columns = ['abs_mean_cont_diff'])
for TF in male_target_contribs.columns:
    #take the difference between the two columns
    sex_differential = abs(np.mean(male_target_contribs[TF]) - np.mean(female_target_contribs[TF]))
    results_df.loc[TF, 'abs_mean_cont_diff'] = sex_differential

In [69]:
male_target_contribs

,ADNP,ADNP2,AEBP1,AEBP2,AHR,AHRR,AIRE,AKNA,ALX4,AR,...,ZSCAN22,ZSCAN23,ZSCAN26,ZSCAN29,ZSCAN31,ZSCAN4,ZSCAN5A,ZSCAN9,ZXDA,ZXDC
0,-0.003126,0.000005,0.022339,-0.000193,0.009005,-0.000124,-0.000083,-0.001430,-0.000028,0.000610,...,0.000013,0.000166,-0.000220,-0.010690,0.000274,0.008390,0.004538,0.000030,-0.000042,0.012300
1,-0.003240,0.000005,0.021931,-0.000186,0.009437,-0.000156,-0.000087,0.000023,-0.000030,0.000463,...,0.000031,0.000174,-0.000242,-0.011036,0.000318,0.008784,0.003539,0.000031,-0.000052,0.011493
2,-0.003463,0.000006,0.023411,-0.000168,0.010078,-0.000166,-0.000093,0.000118,-0.000032,0.000454,...,0.000050,0.000186,-0.000260,-0.011820,0.000349,0.009377,0.003778,0.000034,-0.000047,0.009846
3,-0.003617,0.000006,0.018591,-0.000171,0.010507,-0.000173,-0.000096,0.000016,-0.000033,0.000473,...,0.000052,0.000193,-0.000284,-0.012315,0.000359,0.009769,0.006423,0.000036,-0.000022,0.013177
4,-0.003452,0.000006,0.023298,-0.000152,0.010031,-0.000148,-0.000092,0.000024,-0.000031,0.000454,...,0.000014,0.000185,-0.000255,-0.011745,0.000342,0.009331,0.009327,0.000035,-0.000042,0.011805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,-0.004182,0.000014,0.026326,-0.000134,0.012410,-0.000204,-0.000114,0.000092,-0.000039,0.000597,...,-0.005009,0.000228,-0.000347,-0.014051,0.000460,0.011515,0.004640,0.000029,0.000104,0.007170
709,-0.002683,0.000003,0.019859,-0.000188,0.007633,-0.000126,-0.000070,-0.008173,-0.000024,0.000651,...,0.000106,0.000141,-0.000180,-0.009138,0.000224,0.002558,0.007595,0.000029,-0.000055,0.013400
710,-0.002752,0.000003,0.020309,-0.000203,0.007828,-0.000116,-0.000072,-0.007811,-0.000025,0.000674,...,0.000108,0.000145,-0.000185,-0.009382,0.000227,0.007309,0.008571,0.000027,-0.000047,0.012982
711,-0.002416,0.000003,0.018580,-0.000198,0.006845,-0.000083,-0.000063,-0.009288,-0.000022,0.000572,...,0.000141,0.000127,-0.000163,-0.008233,0.000197,0.002295,0.008908,0.000028,-0.000066,0.012957
712,-0.002406,0.000002,0.018534,-0.000199,0.006815,-0.000080,-0.000063,-0.009290,-0.000021,0.000568,...,0.000155,0.000178,-0.000157,-0.008216,0.000196,0.002285,0.009455,0.000027,-0.000061,0.012946

In [70]:
np.mean(female_target_contribs['ZSCAN9'])

np.float64(3.1003899258855587e-05)

In [71]:
np.mean(male_target_contribs['ZSCAN9'])

np.float64(3.082111450070126e-05)

In [72]:
results_df[results_df['abs_mean_cont_diff'] > 0.009]

Empty DataFrame
Columns: [abs_mean_cont_diff]
Index: []

In [73]:
actual_female_expressions = pd.read_csv('/home/alexanderb/Zhang_lab/data/Full data files/ARCHS4_female_external_expressions.tsv', sep ='\t', index_col = 0)

In [74]:
actual_male_expressions = pd.read_csv('/home/alexanderb/Zhang_lab/data/Full data files/ARCHS4_male_external_expressions.tsv', sep ='\t', index_col = 0)

In [75]:
actual_female_expressions[target]

GSM3662836    1.447158
GSM3662837    1.505150
GSM3662838    1.380211
GSM3662840    1.491362
GSM3662841    1.447158
                ...
GSM3664122    1.819544
GSM3664123    1.623249
GSM3664124    1.755875
GSM3664125    1.785330
GSM3664126    1.748188
Name: MBOAT7, Length: 367, dtype: float64

In [76]:
actual_male_expressions[target]

GSM3662850    1.491362
GSM3662852    0.954243
GSM3662853    1.000000
GSM3662854    1.079181
GSM3662855    0.903090
                ...
GSM3664097    1.342423
GSM3664098    2.230449
GSM3664099    2.245513
GSM3664106    2.346353
GSM3664107    2.301030
Name: MBOAT7, Length: 713, dtype: float64

# Statistical Significance Approach

In [77]:
from scipy.stats import mannwhitneyu

In [78]:
TFs = [None] * len(male_target_contribs.columns)
PVals = [None] * len(male_target_contribs.columns)
for i in range(0, len(male_target_contribs.columns)):
    TFs[i] = male_target_contribs.columns[i]
    #t_statistic, p_value = stats.ttest_ind(male_target_contribs[TFs[i]], female_target_contribs[TFs[i]])
    print(stats.anderson(male_target_contribs[TFs[i]], method = 'interpolate'))
    print(stats.anderson(female_target_contribs[TFs[i]], method = 'interpolate'))
    t_statistic, p_value = mannwhitneyu(male_target_contribs[TFs[i]], female_target_contribs[TFs[i]])
    PVals[i] = p_value
    #dist_diff_dictionary[TF] = {'t_stat' : t_statistic, 'p_val':p_value}

SignificanceResult(statistic=np.float64(27.163547436687395), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.845904023612775), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(125.95933267252894), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(18.212087211040057), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(22.957236357240276), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.079119319080746), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(224.98169864566535), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(10.027814623429094), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.49043371405355), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.180084313329473), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(10.526567665871426), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.113952313394691), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.77538238451291), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.800209138679577), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(43.43122383610455), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(23.70728282233017), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.97233003017584), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.313597341157504), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.51241537993792), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.413653112694419), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(22.8065347907077), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(13.889569381814113), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(23.941542149849397), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.899613601356123), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(191.3763472848076), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(101.66331476263792), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(32.323751437133865), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.600450288726393), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(210.002675867662), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.21804525006445), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(8.681271190668895), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.122759092631213), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(202.92963873841472), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(92.41056481537328), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(97.04393798381705), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(59.156670245341445), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.6622014000842), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.549158145071488), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(57.08084547170847), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.46762597526083), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.81497586946807), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.41339020749399), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.5000182815194876), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.5120521154660764), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(29.782891813221795), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.834459702018307), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(9.260001468798691), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.475398044510598), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(17.164738973741123), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(9.428822448420192), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.9302823096717248), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.189796278700555), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(118.79534438830456), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(57.41129450538767), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.342692522214065), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.575875840725814), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.233097305346519), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(11.78779057762847), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(54.459651798281584), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(34.922170683959735), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(171.62385186220683), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(72.91411440018436), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(16.71146806005447), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(10.793178478287302), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(20.82822875284228), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.60229907215961), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.39588204508732), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.162196732658913), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(114.44592034066488), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(5.54836658173781), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.42912956733005), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.282485132512875), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.206083245924674), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(5.545684493924568), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(18.08591698220698), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.768914434869998), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.071312055529006), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.4009910299399166), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.019516930181), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.369103853028264), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(191.63888516156885), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.6231117474553116), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.736969117140802), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.024208134090486), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.314736051752334), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.998551019153126), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.649569815327254), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(13.179472049182095), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(31.137007111294906), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(9.225833642005682), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.901029849350607), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.449029268788536), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(21.043008950710373), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.659362696364838), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(23.961367219382055), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.900620468121701), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(37.13085945330408), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.04624767642258), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(167.16016594700272), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(93.41868719561131), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(13.559460973902674), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(6.139068556997017), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.456616946450367), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.15131268648895), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(239.36652237287444), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(122.47315886862202), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.019918207334968), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(9.267211182803521), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.395490023830916), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.877874592031105), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(210.98256593388533), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(123.01447178676085), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.405918250814352), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.146053635625151), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.600735244317207), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.750793664321407), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(22.882850883158426), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.224457636232046), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(21.240565866296038), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.19843444152292), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.79375432613574), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.447129646646829), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(67.34654099959118), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(38.34912816314568), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(30.258375257164516), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.039493455183901), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(232.89097953216663), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.801749571332039), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.056631428542005), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(13.913369458268107), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(21.379938210859564), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.424290501845121), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.510099590791242), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.8834002704326167), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.0410074056885605), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.4622243916674051), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.788551733276563), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.66259470330624), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(59.67651098093995), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(36.61483188711975), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(29.227401334125943), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.676186120063903), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(24.524714505744214), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.058340701958855), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.612683703490234), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.527371769480169), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.333231933149591), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.26129007389028), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.081272595313976), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(13.951736812031584), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(241.93579213342878), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(105.49856816750162), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.932053093108607), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.1880940093921026), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(23.21260369774643), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(11.632856340908177), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(175.93775058881351), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(77.64856494802183), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.326694491319813), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.959172679709525), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.570851422220358), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.222183654581727), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.099920232920113), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.062737406314966), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(17.242352030947586), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(11.402837149626464), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(193.67804690123103), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(97.4630897250388), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.451754723156), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.194911992286563), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.996892240261559), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(0.39509808654520384), pvalue=np.float64(0.15))
SignificanceResult(statistic=np.float64(11.826232602529672), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(3.07791683094365), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(21.917448183765146), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(10.165984978158463), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(28.108410701038906), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.084106973423388), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.747011188565352), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.781587675302717), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.126146354367393), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.330847447124256), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(235.91652342232078), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(126.31899384895792), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.41649051142008), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.146087391594676), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(42.850051887240056), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(18.84074762220348), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(29.66161991767467), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.091347755975903), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.300296659398327), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(8.10648697276747), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(231.2684394400584), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(112.75126589112529), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.011637641287507), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(1.4406053598166864), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.624285204180978), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.0727052608699523), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(17.386213934649277), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.914935600769184), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(23.974995293178836), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(10.08002584549638), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(18.389690100865096), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(11.914878709268919), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(21.403222002091184), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(12.312002311631318), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.512138882724685), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(14.996391752410545), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.473679312739819), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(2.8928482211176174), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(17.80761583254855), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(8.877451789622967), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(165.24403965287934), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(81.92435806310868), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.80880979787821), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(8.286173473843178), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(18.287000961320587), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(7.162650822238447), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(115.11249224512494), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(63.07716434847288), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(19.328216563603746), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(9.135431464417252), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(76.82043933548891), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(29.182704783727957), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(27.847622252264387), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(15.072313297465712), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(199.73056357553958), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(94.28714523716707), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(129.09090245630966), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(63.636568934641105), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(11.175096322615445), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(4.8507952690816865), pvalue=np.float64(0.01))
SignificanceResult(statistic=np.float64(26.15140670908636), pvalue=np.float64(0.01))

In [79]:
min(PVals)

np.float64(2.088318929525551e-12)

In [80]:
max(PVals)

np.float64(0.9968775712799703)

In [81]:
#control for multiple testing with BJH correction
adjusted_PVals = stats.false_discovery_control(PVals, method = 'bh')

In [82]:
results_df = pd.DataFrame(columns = ['Gene', 'pval', 'adj_pval'])
results_df['Gene'] = TFs
results_df['pval'] = PVals
results_df['adj_pval'] = adjusted_PVals

In [83]:
#results_df[results_df['adj_pval'] < 0.01].Gene.to_csv(f'./data/diff_contributing_genes/{target}_differential_regulators.csv')

In [84]:

with open(f'./data/diff_contributing_genes/{target}_differential_regulators.txt', 'w+') as f:
    for gene in results_df[results_df['adj_pval'] < 0.05].Gene:
        f.write(f'{gene}\n')
f.close

# visualising final file

In [ ]:
threshold = 0.5
file_path = f'/home/alexanderb/Zhang_lab/MML_model/GRN_reconstruction/data/GW_diff_regulatorts_{threshold}.csv'
results = pd.read_csv(file_path, index_col = 0)

In [ ]:
len(set(results['TF']))

1062

In [ ]:
results

,TF,TG,abs_diff,Male_target_mean_exp,Female_target_mean_exp,target_exp_difference,Male_TF_mean_exp,Female_TF_mean_exp,TF_exp_difference
0,ADNP,A2M,8.512365e-05,3.968651,3.882973,0.085678,2.028400,1.996047,0.032353
1,ADNP2,A2M,1.270273e-03,3.968651,3.882973,0.085678,1.615357,1.557778,0.057579
2,AEBP1,A2M,1.879316e-04,3.968651,3.882973,0.085678,1.498177,1.465411,0.032766
3,AEBP2,A2M,4.428464e-07,3.968651,3.882973,0.085678,1.547696,1.522580,0.025116
4,AHR,A2M,1.200648e-04,3.968651,3.882973,0.085678,2.186099,2.164080,0.022019
...,...,...,...,...,...,...,...,...,...
29713559,ZSCAN31,ZYG11A,inf,0.620619,0.600924,0.019695,1.193735,1.139960,0.053775
29713560,ZSCAN4,ZYG11A,inf,0.620619,0.600924,0.019695,0.034725,0.013944,0.020781
29713561,ZSCAN5A,ZYG11A,inf,0.620619,0.600924,0.019695,0.770906,0.738205,0.032701
29713562,ZSCAN9,ZYG11A,inf,0.620619,0.600924,0.019695,0.900697,0.855865,0.044832
29713563,ZXDA,ZYG11A,inf,0.620619,0.600924,0.019695,0.889706,0.853356,0.036349

In [ ]:
results = results[results['abs_diff'] <= 1000000]

In [ ]:
results[results['abs_diff'] > threshold]

,TF,TG,abs_diff,Male_target_mean_exp,Female_target_mean_exp,target_exp_difference,Male_TF_mean_exp,Female_TF_mean_exp,TF_exp_difference
1091,ATF7,A2ML1,0.248512,0.051510,0.033228,0.018282,1.682430,1.670917,0.011513
1116,CDX1,A2ML1,0.208620,0.051510,0.033228,0.018282,0.005489,0.005881,0.000392
1120,CEBPD,A2ML1,0.398708,0.051510,0.033228,0.018282,2.273552,2.203023,0.070529
1134,CREB5,A2ML1,0.262318,0.051510,0.033228,0.018282,0.682332,0.603223,0.079109
1158,DNMT1,A2ML1,0.223811,0.051510,0.033228,0.018282,1.448468,1.429431,0.019037
...,...,...,...,...,...,...,...,...,...
29339177,ZNF780A,ZMYM2,0.284159,1.955213,1.887137,0.068076,1.416294,1.333914,0.082380
29339178,ZNF808,ZMYM2,0.356145,1.955213,1.887137,0.068076,0.772353,0.744947,0.027406
29339179,ZNF821,ZMYM2,0.252643,1.955213,1.887137,0.068076,0.573692,0.568376,0.005316
29339180,ZNF93,ZMYM2,0.253160,1.955213,1.887137,0.068076,0.379757,0.351418,0.028339
29339181,ZSCAN23,ZMYM2,0.223938,1.955213,1.887137,0.068076,0.054576,0.054833,0.000257

In [ ]:
results.to_csv(file_path)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.scatterplot(results, x = 'Exp_difference', y = 'abs_diff', size = 3, color = 'darkblue', alpha = 0.5, legend = False)

ValueError: Could not interpret value `Exp_difference` for `x`. An entry with this name does not appear in `data`.

In [ ]:
diff_regulated = set(results['TG'])
diff_regulators = set(results['TF'])

In [ ]:
len(diff_regulators)

1062

In [ ]:
len(diff_regulated)

275

In [ ]:
with open(f'./data/{threshold}_differential_regulated.txt', 'w+') as f:
    for gene in diff_regulated:
        f.write(f'{gene}\n')
f.close

In [ ]:
with open(f'./data/{threshold}_differential_regulators.txt', 'w+') as f:
    for gene in diff_regulators:
        f.write(f'{gene}\n')
f.close

In [ ]:
target = 'CYP4'
results[results['TF'] == target]

Empty DataFrame
Columns: [TF, TG, abs_diff, Male_mean_exp, Female_mean_exp, Exp_difference]
Index: []

In [ ]:
results[results['TG'] == target].to_csv(f'{file_path}_{target}.csv')